server:
  port: 8302
  
spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://sgim-eureka-service.herokuapp.com/eureka/

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8302/eureka/