server:
  port: 8302
  
spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    hostname: microservice.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: http://eureka.herokuapp.com/eureka/
      non-secure-port: 80
      secure-port: 443

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8302/eureka/